---
title: "MAS-12-code"
output: html_document
date: '2022-11-09'
---
## Library Package
---
```{r}
library(tm)
library(MASS)
library(base)
```


## Data input
```{r}
# 1. Iris data
data(iris3)
head(iris)
```


```{r}
# 2. Leptograpsus variegatus crabs data
data("crabs")
head(crabs)
```

\newpage

## 1. Discriminant Analysis

### 1-1) Linear discriminant analysis
```{r, fig.height=4}

#In chapter 11, iris dataset
ir <- rbind(iris3[,,1], iris3[,,2], iris3[,,3])
ir.species <- factor(c(rep("s", 50), rep("c", 50), rep("v", 50)))

#In chapter 12, iris dataset
ir.lda <- lda(log(ir), ir.species)
ir.ld <- predict(ir.lda, dirnen =2)$x
ir.ld[,1]<--ir.ld[,1]

eqscplot(ir.ld, type = "n", xlab = "first linear discrirninant" ,
         ylab = "second linear discrirninant")

text(ir.ld, labels = as.character(ir.species[-143]), 
     col =3 + as.integer(ir.species), cex =0.8)
```


```{r, fig.height=4}
# Leptograpsus variegatus crabs dat
#chapter 11, crabs dataset
lcrabs <- log(crabs[,4:8])
crabs.grp <- factor(c("B", "b", "O", "o")[rep(1:4, each = 50)])

#chapter 12, crabs dataset
(dcrabs.lda <- lda(crabs$sex ~ FL + RW + CL + CW, lcrabs))
table(crabs$sex, predict(dcrabs.lda)$class)


(dcrabs.lda4 <- lda(crabs.grp ~ FL + RW + CL + CW, lcrabs))
dcrabs.pr4 <- predict(dcrabs.lda4, dimen =2)
dcrabs.pr2 <- dcrabs.pr4$post[, c("B", "O")] %*% c(1, 1)
table(crabs$sex, dcrabs.pr2 > 0.5)


cr.t <- dcrabs.pr4$x[, 1:2]
#print(cr.t)
cr.t[,2]<--cr.t[,2]
eqscplot(cr.t, type='n',xlab = "First LD", ylab = "Second LD") 
text(cr.t, labels =as.character(crabs.grp))

perp <- function(x, y) {
  m <- (x+y)/2
  s <- - (x[1] - y[1])/(x[2] - y[2])
  abline(c(m[2] - s*m[1] , s))
  invisible()
}
cr.m <- lda(cr.t, crabs$sex)$means
points(cr.m, pch = 3, mkh = 0.3)
perp(cr.m[1, ], cr.m[2, ])
cr.lda <- lda(cr.t, crabs.grp)


x <- seq(-6, 6, 0.25)
y <- seq(-2, 2, 0.25)
Xcon <- matrix(c(rep(x,length(y)), rep(y, each = length(x))) ,ncol=2) 
#print(Xcon)
cr.pr <- predict(cr.lda, Xcon)$post[, c("B", "O")] %*% c(1,1) 
contour(x, y, matrix(cr.pr, length(x), length(y)),levels = 0.5, labex = 0, add = T, lty= 3)

for(i in c("O", "o", "B", "b"))
  print(var(lcrabs[crabs.grp == i, ]))



fgl.ld <- predict(lda(type ~ ., fgl), dirnen = 2)$x 
eqscplot(fgl.ld, type = "n", xlab = "LD1", ylab = "LD2") 
# #either
# for(i in seq(along = levels(fgl$type))) {
# 	set <- fgl$type[-40] == levels(fgl$type)[i]
# 	points(fgl.ld[set,], pch = 18, cex = 0.6, col = 2 + i)}
#key(text = list (levels (fgl$type), col = 3:8))
# or
text(fgl.ld, cex = 0.6,
labels = c ("F", "N", "V", "C", "T", "H") [fgl$type [-40]] )

fgl.rld <- predict(lda(type ~ ., fgl, method = "t"), dimen = 2)$x 
eqscplot(fgl.rld, type = "n", xlab = "LD1", ylab = "LD2")
# either
# for(i in seq(along = levels(fgl$type))) {
# 	set <- fgl$type[-40] == levels(fgl$type)[i]
# 	points(fgl.rld[set,], pch = 18, cex = 0.6, col = 2 + i)}
#key(text = list (levels (fgl$type), col = 3:8))
# or
text(fgl.rld, cex =0.6, labels = c("F", "N", "V", "C", "T", "H")[fgl$type[-40]])
```

### 1-2) Classification Theory
```{r}

#decrease len if you have little memory.
predplot <- function(object, main="", len = 100, ...)
{
    plot(Cushings[,1], Cushings[,2], log="xy", type="n",
         xlab = "Tetrahydrocortisone", ylab = "Pregnanetriol", main = main)
    for(il in 1:4) {
        set <- Cushings$Type==levels(Cushings$Type)[il]
        text(Cushings[set, 1], Cushings[set, 2],
             labels=as.character(Cushings$Type[set]), col = 2 + il) }
    xp <- seq(0.6, 4.0, length=len)
    yp <- seq(-3.25, 2.45, length=len)
    cushT <- expand.grid(Tetrahydrocortisone = xp,
                         Pregnanetriol = yp)
    Z <- predict(object, cushT, ...); zp <- as.numeric(Z$class)
    zp <- Z$post[,3] - pmax(Z$post[,2], Z$post[,1])
    contour(exp(xp), exp(yp), matrix(zp, len),
            add = TRUE, levels = 0, labex = 0)
    zp <- Z$post[,1] - pmax(Z$post[,2], Z$post[,3])
    contour(exp(xp), exp(yp), matrix(zp, len),
            add = TRUE, levels = 0, labex = 0)
    invisible()
}

cushplot <- function(xp, yp, Z)
{
    plot(Cushings[, 1], Cushings[, 2], log = "xy", type = "n",
         xlab = "Tetrahydrocortisone", ylab = "Pregnanetriol")
    for(il in 1:4) {
        set <- Cushings$Type==levels(Cushings$Type)[il]
        text(Cushings[set, 1], Cushings[set, 2],
             labels = as.character(Cushings$Type[set]), col = 2 + il) }
    zp <- Z[, 3] - pmax(Z[, 2], Z[, 1])
    contour(exp(xp), exp(yp), matrix(zp, np),
            add = TRUE, levels = 0, labex = 0)
    zp <- Z[, 1] - pmax(Z[, 2], Z[, 3])
    contour(exp(xp), exp(yp), matrix(zp, np),
            add = TRUE, levels = 0, labex = 0)
    invisible()
}

cush <- log(as.matrix(Cushings[, -3]))
tp <- Cushings$Type[1:21, drop = TRUE]
cush.lda <- lda(cush[1:21,], tp); predplot(cush.lda, "LDA")
cush.qda <- qda(cush[1:21,], tp); predplot(cush.qda, "QDA")
predplot(cush.qda, "QDA (predictive)", method = "predictive")
predplot(cush.qda, "QDA (debiased)", method = "debiased")

Cf <- data.frame(tp = tp,
  Tetrahydrocortisone = log(Cushings[1:21, 1]),
  Pregnanetriol = log(Cushings[1:21, 2]) )
cush.multinom <- multinom(tp ~ Tetrahydrocortisone
  + Pregnanetriol, Cf, maxit = 250)
xp <- seq(0.6, 4.0, length = 100); np <- length(xp)
yp <- seq(-3.25, 2.45, length = 100)
cushT <- expand.grid(Tetrahydrocortisone = xp,
                     Pregnanetriol = yp)
Z <- predict(cush.multinom, cushT, type = "probs")
cushplot(xp, yp, Z)

library(tree)
cush.tr <- tree(tp ~ Tetrahydrocortisone + Pregnanetriol, Cf)
plot(cush[, 1], cush[, 2], type = "n",
    xlab = "Tetrahydrocortisone", ylab = "Pregnanetriol")
for(il in 1:4) {
 set <- Cushings$Type==levels(Cushings$Type)[il]
 text(cush[set, 1], cush[set, 2],
      labels = as.character(Cushings$Type[set]), col = 2 + il) }
par(cex = 1.5); partition.tree(cush.tr, add = TRUE); par(cex = 1)

```

